# This file was generated by GoReleaser. DO NOT EDIT.
cask "nokey" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "aba352bfa99e89cbae830e0ff2a7cdce9322e19ea676eaf005689cc57531e003"
      url "https://github.com/nokey-ai/nokey/releases/download/v#{version}/nokey_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c47731ff7efb32fe39a5f0ecf7a8384bd31568f26a1555071717936f9adab1a0"
      url "https://github.com/nokey-ai/nokey/releases/download/v#{version}/nokey_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7a61fc364e24c11f4567178729d8cf21e7343813887db935f31342ac0e0d0bb4"
      url "https://github.com/nokey-ai/nokey/releases/download/v#{version}/nokey_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8695ee9c20ec5024be9a62ba11b85c7b947ad0e69210c87379863362b3ced68a"
      url "https://github.com/nokey-ai/nokey/releases/download/v#{version}/nokey_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nokey"
  desc "Zero-trust secret management for AI coding assistants"
  homepage "https://github.com/nokey-ai/nokey"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nokey"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nokey"]
    end
  end

  # No zap stanza required

end
