# This file was generated by GoReleaser. DO NOT EDIT.
cask "nokey" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "2cec94af1d89200c5a934548c6f8b1db5ce04711398e81f38b5ccecef321d0c7"
      url "https://github.com/nokey-ai/nokey/releases/download/v#{version}/nokey_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5c220c4ccc38f372a465244d2d8e73b737387fee27df3a92ab34a78499c41b6a"
      url "https://github.com/nokey-ai/nokey/releases/download/v#{version}/nokey_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3ace13dc8c8d4fdd12c13a8048008286f82fa1dc30ea20c0ae25664eb37269b4"
      url "https://github.com/nokey-ai/nokey/releases/download/v#{version}/nokey_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e0f72906a24aa03eb9439d435b629cb1358fbdf570a0b31ba30e495aeeabfc8e"
      url "https://github.com/nokey-ai/nokey/releases/download/v#{version}/nokey_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nokey"
  desc "Zero-trust secret management for AI coding assistants"
  homepage "https://github.com/nokey-ai/nokey"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nokey"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nokey"]
    end
  end

  # No zap stanza required

end
