# This file was generated by GoReleaser. DO NOT EDIT.
cask "nokey" do
  name "nokey"
  desc "Zero-trust secret management for AI coding assistants"
  homepage "https://github.com/nokey-ai/nokey"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nokey"

  on_macos do
    on_intel do
      url "https://github.com/nokey-ai/nokey/releases/download/v#{version}/nokey_#{version}_darwin_amd64.tar.gz"
      sha256 "fd7efea06e23c23fba1d5ed352a8de5baad5dd54850aff425042126c612ab312"
    end
    on_arm do
      url "https://github.com/nokey-ai/nokey/releases/download/v#{version}/nokey_#{version}_darwin_arm64.tar.gz"
      sha256 "06e0d59ab6e344ab108859d777068b0d2971a15a96f80ba7e0bf1d109b541224"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nokey-ai/nokey/releases/download/v#{version}/nokey_#{version}_linux_amd64.tar.gz"
      sha256 "d5f8ee92ae0bf94535d7fdf150dfafa13fd1fbc38da260e6b735813551e0267e"
    end
    on_arm do
      url "https://github.com/nokey-ai/nokey/releases/download/v#{version}/nokey_#{version}_linux_arm64.tar.gz"
      sha256 "e8d15a88281b1a53f25d63f458f75f312f455f3d358d4425141db4dc2d381c62"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nokey"]
    end
  end

  # No zap stanza required
end
